- name: demo on conditions
  hosts: local
  connection: local
  vars:
    IS_LIVE: false # task executes only when IS_LIVE is true otherwise it skips

  tasks:
  - name: check live or not
    ansible.builtin.debug:
      msg: "Yes, It is live"
    when: IS_LIVE